// TermsPage.jsx
import React from "react";
import { Link } from "react-router-dom";

const lastUpdated = "September 22, 2025";
const contactEmail = "info@campsync.ai"; // replace with your contact

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white p-10 shadow-md rounded-lg">
        <h1 className="text-3xl font-bold text-gray-900 mb-4">Terms &amp; Conditions</h1>
        <p className="text-sm text-gray-500 mb-6">Last updated: {lastUpdated}</p>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
          <p className="text-gray-700">
            These Terms &amp; Conditions ("Terms") govern your access to and use of the platform CampusConnect.AI
            ("Platform", "we", "us", or "our"). By accessing or using the Platform you agree to be bound by these
            Terms. If you do not agree with any part of these Terms, you must not use the Platform.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">2. Definitions</h2>
          <p className="text-gray-700">
            <strong>User / You:</strong> any person who uses the Platform, including students and alumni.
          </p>
          <p className="text-gray-700">
            <strong>Content:</strong> includes text, uploads, interview experiences, question papers, comments,
            and any materials provided by users or generated by Platform features (including AI outputs).
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">3. Use of the Platform</h2>
          <p className="text-gray-700">
            The Platform is provided for educational and placement preparation purposes. You agree to use the Platform
            only for lawful purposes and in accordance with these Terms. You must not:
          </p>
          <ul className="list-disc list-inside text-gray-700 mt-2">
            <li>Share content that is illegal, defamatory, obscene, hateful, or infringes third-party rights.</li>
            <li>Impersonate another person or create multiple accounts to manipulate Platform features.</li>
            <li>Attempt to circumvent, interfere with, or compromise security or integrity of the Platform.</li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">4. Accounts &amp; Security</h2>
          <p className="text-gray-700">
            You are responsible for maintaining the confidentiality of your account credentials. Notify us immediately
            of any unauthorized access or use. We are not responsible for losses resulting from unauthorized use of your
            account unless caused by our gross negligence.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">5. User Content, Uploads &amp; Intellectual Property</h2>
          <p className="text-gray-700">
            By uploading or submitting Content to the Platform you represent and warrant that you own or have the right
            to share that Content and that sharing does not violate any law or third-party rights.
          </p>
          <p className="text-gray-700 mt-2">
            You grant the Platform a non-exclusive, worldwide, royalty-free license to use, host, store, reproduce,
            and display your Content to operate and improve the Platform (including anonymized use for analytics and
            training of internal models). You may remove your Content where the Platform provides such functionality,
            subject to any applicable backups or caches.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">6. AI Outputs &amp; Disclaimer</h2>
          <p className="text-gray-700">
            The Platform may use AI components (LLMs / NLP) to generate suggestions, recommendations, and interview
            simulations. AI outputs are provided for educational guidance only and may be incorrect, incomplete, or
            outdated. Always verify critical information independently. We disclaim liability for decisions made based
            on AI outputs.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">7. Prohibited Content &amp; Copyright</h2>
          <p className="text-gray-700">
            Do not upload materials you do not have permission to share (e.g., copyrighted exam papers not owned by
            you or distribution-protected materials). If you believe your copyright has been infringed, contact the
            Platform administrator at <a href={`mailto:${contactEmail}`} className="text-indigo-600">{contactEmail}</a>.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">8. Account Suspension &amp; Termination</h2>
          <p className="text-gray-700">
            We reserve the right to suspend or terminate accounts that violate these Terms or where necessary to protect
            the Platform. Termination does not waive any rights or remedies we may have.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">9. Limitation of Liability</h2>
          <p className="text-gray-700">
            To the extent permitted by law, CampusConnect.AI and its maintainers will not be liable for indirect,
            incidental, special, or consequential damages arising from your use of the Platform. Our maximum liability
            for direct damages is limited to amounts actually paid by you (if any) for use of the Platform.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">10. Indemnification</h2>
          <p className="text-gray-700">
            You agree to indemnify and hold harmless CampusConnect.AI and its officers, agents and employees from any
            claims, liabilities or expenses arising from your breach of these Terms or your uploaded Content.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">11. Changes to Terms</h2>
          <p className="text-gray-700">
            We may update these Terms from time to time. We will post the revised Terms on this page with an updated
            "Last updated" date. Continued use after changes indicates acceptance.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">12. Governing Law &amp; Dispute Resolution</h2>
          <p className="text-gray-700">
            These Terms are governed by the laws of India. Any disputes will be subject to the exclusive jurisdiction
            of the courts in your state or territory, to the extent permitted by law.
          </p>
        </section>

        <section className="mt-8">
          <p className="text-gray-700">
            If you have questions about these Terms, contact us at{" "}
            <a href={`mailto:${contactEmail}`} className="text-indigo-600">{contactEmail}</a>.
          </p>
        </section>
      </div>
      <div className="mt-8 flex justify-center">
              <Link
                  to="/"
                  className="px-6 py-2 bg-indigo-600 text-white font-medium rounded-lg shadow hover:bg-indigo-700 transition"
              >
                  Back to Home
              </Link>
      </div>
    </div>
  );
}
